# Generated by Django 5.1.6 on 2025-03-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="user_avatar/", verbose_name="Аватар"
            ),
        ),
    ]
